import teamMember1 from "@/assets/images/teamMember/teamMember1.png";
import teamMember2 from "@/assets/images/teamMember/teamMember2.png";
import teamMember3 from "@/assets/images/teamMember/teamMember3.png";
import user1 from "@/assets/images/users/user1.jpg";
import user2 from "@/assets/images/users/user2.jpg";
import user3 from "@/assets/images/users/user3.jpg";
import user4 from "@/assets/images/users/user4.jpg";
import user5 from "@/assets/images/users/user5.jpg";
import user6 from "@/assets/images/users/user6.jpg";
import user7 from "@/assets/images/users/user7.jpg";
import user8 from "@/assets/images/users/user8.jpg";
import user9 from "@/assets/images/users/user9.jpg";

export const userReviews = [
  {
    name: "علی بهرامی",
    role: "customer",
    image: user1,
    review:
      "محصولات خیلی باکیفیتی دارید! من از خرید روغن زیتون خیلی راضی بودم.",
  },
  {
    name: "مریم رضایی",
    role: "customer",
    image: user2,
    review:
      "بسته‌بندی خیلی خوب بود و کاملاً طبیعی و تازه. حتماً دوباره خرید می‌کنم.",
  },
  {
    name: "سعید محمدی",
    role: "customer",
    image: user3,
    review: "عسل ارگانیک شما فوق‌العاده بود! طعمش کاملاً طبیعی و خوشمزه بود.",
  },
  {
    name: "زهرا احمدی",
    role: "customer",
    image: user4,
    review: "چای گیاهی‌ای که خریدم خیلی عطر خوبی داره. عالی بود!",
  },
  {
    name: "رضا نوری",
    role: "customer",
    image: user5,
    review: "قیمت‌ها خیلی مناسبه و کیفیت محصولات هم بالاست. پیشنهاد می‌کنم!",
  },
  {
    name: "نسترن کریمی",
    role: "customer",
    image: user6,
    review: "تحویل سریع بود و محصولات کاملاً تازه و ارگانیک. تجربه عالی بود.",
  },
  {
    name: "امیر حسینی",
    role: "customer",
    image: user7,
    review: "خیلی دوست داشتم که روی بسته‌بندی‌ها اطلاعات کامل نوشته شده بود.",
  },
  {
    name: "الهام نظری",
    role: "customer",
    image: user8,
    review: "محصولات شما حس خوبی داره، مخصوصاً روغن نارگیل که امتحان کردم.",
  },
  {
    name: "محمد صادقی",
    role: "customer",
    image: user9,
    review: "همه چیز عالی بود، فقط اگر تنوع محصولات بیشتر بشه خیلی بهتره.",
  },
  {
    name: "سحر تیموری",
    role: "customer",
    image: user1,
    review: "خیلی ممنون از محصولات باکیفیتتون! حتماً دوباره خرید می‌کنم.",
  },
];

export const teamMembers = [
  { name: "مهدی رضایی", job: "مدیر ارشد محصول", image: teamMember1 },
  { name: "لیلا اسلامی", job: "مسئول روابط عمومی", image: teamMember2 },
  { name: "سارا محمودی", job: "کارشناس کیفیت", image: teamMember3 },
  { name: "امیر حسین زاده", job: "مدیر اجرایی", image: teamMember1 },
  { name: "شهرزاد صالحی", job: "مدیر مارکتینگ", image: teamMember2 },
  { name: "حمید کاشانی", job: "توسعه‌دهنده ارگانیک", image: teamMember3 },
  { name: "ندا فاضلی", job: "مشاور تغذیه", image: teamMember1 },
  { name: "علی آقایی", job: "کارشناس تامین منابع", image: teamMember2 },
  { name: "محمدرضا حسینی", job: "کارشناس خرید", image: teamMember3 },
  { name: "مریم حیدری", job: "مدیر عملیات", image: teamMember1 },
];

export const categoriesFilters = [
  { name: "گیاهی", id: 1 },
  { name: "ارگانیک", id: 2 },
  { name: "میوه", id: 3 },
  { name: "آب میوه", id: 4 },
];

export const socialMediaArr = [
  {
    name: "instagram",
    img: "https://www.svgrepo.com/show/452229/instagram-1.svg",
  },
  {
    name: "telegram",
    img: "https://www.svgrepo.com/show/349527/telegram.svg",
  },
  {
    name: "whatsapp",
    img: "https://www.svgrepo.com/show/349563/whatsapp.svg",
  },
  {
    name: "youtube",
    img: "https://www.svgrepo.com/show/349577/youtube.svg",
  },
];

export const products = [
  {
    name: "سیب",
    price: 95000,
    stars: 4,
    id: 1,
    category: "میوه",
    discount: 20,
    stock: true,
    description: "سیب تازه و آبدار از باغ‌های شمال ایران.",
    img: "https://www.svgrepo.com/show/484901/apple.svg",
  },
  {
    name: "روغن گیاهی",
    price: 230000,
    stars: 5,
    id: 2,
    category: "گیاهی",
    discount: 15,
    stock: true,
    description: "روغن گیاهی خالص و بدون افزودنی.",
    img: "https://www.svgrepo.com/show/299854/oil-olive-oil.svg",
  },
  {
    name: "عسل طبیعی",
    price: 650000,
    stars: 4,
    id: 3,
    category: "ارگانیک",
    discount: 10,
    stock: true,
    description: "عسل طبیعی از زنبورداران محلی.",
    img: "https://www.svgrepo.com/show/396648/honey-pot.svg",
  },
  {
    name: "فلفل دلمه",
    price: 80000,
    stars: 4,
    id: 4,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "فلفل دلمه‌ای تازه و باکیفیت.",
    img: "https://www.svgrepo.com/show/356638/pepper-bell-01.svg",
  },
  {
    name: "ذرت",
    price: 75000,
    stars: 2,
    id: 5,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "ذرت شیرین و تازه.",
    img: "https://www.svgrepo.com/show/276195/corn.svg",
  },
  {
    name: "آب هویج",
    price: 90000,
    stars: 5,
    id: 6,
    category: "ارگانیک",
    discount: 25,
    stock: true,
    description: "آب هویج طبیعی و سرشار از ویتامین.",
    img: "https://www.svgrepo.com/show/1291/carrot-juice.svg",
  },
  {
    name: "موز",
    price: 120000,
    stars: 3,
    id: 7,
    category: "میوه",
    discount: 0,
    stock: false,
    description: "موز رسیده و شیرین.",
    img: "https://www.svgrepo.com/show/399944/banana.svg",
  },
  {
    name: "پرتقال",
    price: 85000,
    stars: 4,
    id: 8,
    category: "میوه",
    discount: 30,
    stock: true,
    description: "پرتقال آبدار و شیرین.",
    img: "https://www.svgrepo.com/show/474519/orange.svg",
  },
  {
    name: "انگور",
    price: 110000,
    stars: 5,
    id: 9,
    category: "میوه",
    discount: 0,
    stock: true,
    description: "انگور سیاه و قرمز تازه.",
    img: "https://www.svgrepo.com/show/530211/grape.svg",
  },
  {
    name: "توت فرنگی",
    price: 150000,
    stars: 4,
    id: 10,
    category: "میوه",
    discount: 40,
    stock: false,
    description: "توت فرنگی شیرین و خوش‌عطر.",
    img: "https://www.svgrepo.com/show/400795/strawberry.svg",
  },
  {
    name: "کیوی",
    price: 130000,
    stars: 3,
    id: 11,
    category: "میوه",
    discount: 0,
    stock: true,
    description: "کیوی تازه و پر از ویتامین C.",
    img: "https://www.svgrepo.com/show/396850/kiwi-fruit.svg",
  },
  {
    name: "آناناس",
    price: 200000,
    stars: 5,
    id: 12,
    category: "میوه",
    discount: 50,
    stock: true,
    description: "آناناس شیرین و آبدار.",
    img: "https://www.svgrepo.com/show/194367/pineapple.svg",
  },
  {
    name: "هلو",
    price: 90000,
    stars: 4,
    id: 13,
    category: "میوه",
    discount: 0,
    stock: false,
    description: "هلو آبدار و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/406857/peach.svg",
  },
  {
    name: "زردآلو",
    price: 80000,
    stars: 3,
    id: 14,
    category: "میوه",
    discount: 10,
    stock: true,
    description: "زردآلو تازه و شیرین.",
    img: "https://www.svgrepo.com/show/454327/apricot-food-fruit.svg",
  },
  {
    name: "گیلاس",
    price: 170000,
    stars: 5,
    id: 15,
    category: "میوه",
    discount: 0,
    stock: true,
    description: "گیلاس قرمز و آبدار.",
    img: "https://www.svgrepo.com/show/454322/cherries-cherry-fruit-food.svg",
  },
  {
    name: "روغن زیتون",
    price: 300000,
    stars: 5,
    id: 16,
    category: "گیاهی",
    discount: 20,
    stock: false,
    description: "روغن زیتون خالص و باکیفیت.",
    img: "https://www.svgrepo.com/show/299854/oil-olive-oil.svg",
  },
  {
    name: "روغن نارگیل",
    price: 250000,
    stars: 4,
    id: 17,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "روغن نارگیل طبیعی و خالص.",
    img: "https://www.svgrepo.com/show/476868/coconut-cocktail.svg",
  },
  {
    name: "روغن کنجد",
    price: 280000,
    stars: 4,
    id: 18,
    category: "گیاهی",
    discount: 15,
    stock: true,
    description: "روغن کنجد خالص و سرشار از آنتی‌اکسیدان.",
    img: "https://www.svgrepo.com/show/341550/soy-sauce-ketchup.svg",
  },
  {
    name: "روغن آفتابگردان",
    price: 220000,
    stars: 3,
    id: 19,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "روغن آفتابگردان با کیفیت بالا.",
    img: "https://www.svgrepo.com/show/407548/sunflower.svg",
  },
  {
    name: "روغن بادام",
    price: 350000,
    stars: 5,
    id: 20,
    category: "گیاهی",
    discount: 25,
    stock: true,
    description: "روغن بادام طبیعی و مرغوب.",
    img: "https://www.svgrepo.com/show/130850/jordan-almond.svg",
  },
  {
    name: "روغن ذرت",
    price: 180000,
    stars: 3,
    id: 21,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "روغن ذرت مناسب برای پخت و پز.",
    img: "https://www.svgrepo.com/show/341550/soy-sauce-ketchup.svg",
  },
  {
    name: "روغن سویا",
    price: 200000,
    stars: 4,
    id: 22,
    category: "گیاهی",
    discount: 10,
    stock: false,
    description: "روغن سویا با کیفیت عالی.",
    img: "https://www.svgrepo.com/show/341550/soy-sauce-ketchup.svg",
  },
  {
    name: "عسل طبیعی",
    price: 650000,
    stars: 5,
    id: 23,
    category: "ارگانیک",
    discount: 0,
    stock: true,
    description: "عسل طبیعی از زنبورداران محلی.",
    img: "https://www.svgrepo.com/show/396648/honey-pot.svg",
  },
  {
    name: "چای سبز",
    price: 120000,
    stars: 4,
    id: 24,
    category: "ارگانیک",
    discount: 30,
    stock: true,
    description: "چای سبز ارگانیک و باکیفیت.",
    img: "https://www.svgrepo.com/show/299863/tea-cup-food-and-restaurant.svg",
  },
  {
    name: "قهوه ارگانیک",
    price: 300000,
    stars: 5,
    id: 25,
    category: "ارگانیک",
    discount: 0,
    stock: false,
    description: "قهوه ارگانیک با عطر و طعم بی‌نظیر.",
    img: "https://www.svgrepo.com/show/457279/coffee-coarse.svg",
  },
  {
    name: "شکر قهوه‌ای",
    price: 90000,
    stars: 3,
    id: 26,
    category: "ارگانیک",
    discount: 5,
    stock: true,
    description: "شکر قهوه‌ای طبیعی و سالم.",
    img: "https://www.svgrepo.com/show/475226/sugar.svg",
  },
  {
    name: "آرد گندم کامل",
    price: 110000,
    stars: 4,
    id: 27,
    category: "ارگانیک",
    discount: 0,
    stock: true,
    description: "آرد گندم کامل و ارگانیک.",
    img: "https://www.svgrepo.com/show/276552/flour.svg",
  },
  {
    name: "سرکه سیب",
    price: 150000,
    stars: 5,
    id: 28,
    category: "ارگانیک",
    discount: 20,
    stock: true,
    description: "سرکه سیب طبیعی و مفید برای سلامتی.",
    img: "https://www.svgrepo.com/show/223359/vinegar.svg",
  },
  {
    name: "کره بادام زمینی",
    price: 200000,
    stars: 4,
    id: 29,
    category: "ارگانیک",
    discount: 0,
    stock: false,
    description: "کره بادام زمینی خالص و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/297779/butter-jar-cocoa.svg",
  },
  {
    name: "سیب زمینی",
    price: 50000,
    stars: 3,
    id: 30,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "سیب زمینی تازه و باکیفیت.",
    img: "https://www.svgrepo.com/show/398113/potato.svg",
  },
  {
    name: "پیاز",
    price: 40000,
    stars: 2,
    id: 31,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "پیاز تازه و مرغوب.",
    img: "https://www.svgrepo.com/show/356687/onion-01.svg",
  },
  {
    name: "سیر",
    price: 70000,
    stars: 4,
    id: 32,
    category: "گیاهی",
    discount: 15,
    stock: false,
    description: "سیر تازه و پرخاصیت.",
    img: "https://www.svgrepo.com/show/396549/garlic.svg",
  },
  {
    name: "گوجه فرنگی",
    price: 60000,
    stars: 3,
    id: 33,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "گوجه فرنگی تازه و آبدار.",
    img: "https://www.svgrepo.com/show/407629/tomato.svg",
  },
  {
    name: "خیار",
    price: 45000,
    stars: 2,
    id: 34,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "خیار تازه و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/396244/cucumber.svg",
  },
  {
    name: "کاهو",
    price: 30000,
    stars: 3,
    id: 35,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "کاهو تازه و ترد.",
    img: "https://www.svgrepo.com/show/475202/lettuce.svg",
  },
  {
    name: "هویج",
    price: 55000,
    stars: 4,
    id: 36,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "هویج تازه و شیرین.",
    img: "https://www.svgrepo.com/show/395982/carrot.svg",
  },
  {
    name: "فلفل قرمز",
    price: 75000,
    stars: 3,
    id: 37,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "فلفل قرمز تند و تازه.",
    img: "https://www.svgrepo.com/show/356641/pepper-chili.svg",
  },
  {
    name: "بادمجان",
    price: 80000,
    stars: 4,
    id: 38,
    category: "گیاهی",
    discount: 20,
    stock: true,
    description: "بادمجان تازه و باکیفیت.",
    img: "https://www.svgrepo.com/show/434057/eggplant.svg",
  },
  {
    name: "کدو سبز",
    price: 65000,
    stars: 3,
    id: 39,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "کدو سبز تازه و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/223292/pumpkin.svg",
  },
  {
    name: "لوبیا سبز",
    price: 90000,
    stars: 4,
    id: 40,
    category: "گیاهی",
    discount: 15,
    stock: true,
    description: "لوبیا سبز تازه و پرخاصیت.",
    img: "https://www.svgrepo.com/show/263352/beans.svg",
  },
  {
    name: "نخود فرنگی",
    price: 85000,
    stars: 3,
    id: 41,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "نخود فرنگی تازه و شیرین.",
    img: "https://www.svgrepo.com/show/475212/peas.svg",
  },
  {
    name: "کلم بروکلی",
    price: 120000,
    stars: 4,
    id: 42,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "کلم بروکلی تازه و سرشار از ویتامین.",
    img: "https://www.svgrepo.com/show/395941/broccoli.svg",
  },
  {
    name: "گل کلم",
    price: 110000,
    stars: 3,
    id: 43,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "گل کلم تازه و باکیفیت.",
    img: "https://www.svgrepo.com/show/489686/cauliflower.svg",
  },
  {
    name: "کلم پیچ",
    price: 95000,
    stars: 4,
    id: 44,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "کلم پیچ تازه و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/489686/cauliflower.svg",
  },
  {
    name: "اسفناج",
    price: 70000,
    stars: 3,
    id: 45,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "اسفناج تازه و پرخاصیت.",
    img: "https://www.svgrepo.com/show/295468/spinach.svg",
  },
  {
    name: "جعفری",
    price: 30000,
    stars: 2,
    id: 46,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "جعفری تازه و خوش‌عطر.",
    img: "https://www.svgrepo.com/show/475200/kohlrabi.svg",
  },
  {
    name: "شوید",
    price: 35000,
    stars: 2,
    id: 47,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "شوید تازه و پرخاصیت.",
    img: "https://www.svgrepo.com/show/475193/dolmades.svg",
  },
  {
    name: "تربچه",
    price: 40000,
    stars: 3,
    id: 48,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "تربچه تازه و ترد.",
    img: "https://www.svgrepo.com/show/475221/radish.svg",
  },
  {
    name: "شلغم",
    price: 50000,
    stars: 2,
    id: 49,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "شلغم تازه و مفید برای سلامتی.",
    img: "https://www.svgrepo.com/show/207770/turnip.svg",
  },
  {
    name: "چغندر",
    price: 60000,
    stars: 3,
    id: 50,
    category: "گیاهی",
    discount: 15,
    stock: true,
    description: "چغندر تازه و سرشار از آنتی‌اکسیدان.",
    img: "https://www.svgrepo.com/show/209820/beet.svg",
  },
  {
    name: "زنجبیل",
    price: 150000,
    stars: 4,
    id: 51,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "زنجبیل تازه و پرخاصیت.",
    img: "https://www.svgrepo.com/show/356644/ginger.svg",
  },
  {
    name: "زعفران",
    price: 1000000,
    stars: 5,
    id: 52,
    category: "گیاهی",
    discount: 20,
    stock: true,
    description: "زعفران اصل و باکیفیت.",
    img: "https://img.icons8.com/?size=100&id=Mpx3yHOnJJvR&format=png&color=000000",
  },
  {
    name: "دارچین",
    price: 200000,
    stars: 4,
    id: 53,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "دارچین خالص و خوش‌عطر.",
    img: "https://www.svgrepo.com/show/215641/cinnamon-roll-sweet.svg",
  },
  {
    name: "هل",
    price: 250000,
    stars: 4,
    id: 54,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "هل تازه و خوش‌بو.",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsPe4OmBmFR8JLlvti6PFsg7eb0NLekZIlhQ&s",
  },
  {
    name: "زردچوبه",
    price: 90000,
    stars: 3,
    id: 55,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "زردچوبه خالص و پرخاصیت.",
    img: "https://www.svgrepo.com/show/285064/proteins-powder.svg",
  },
  {
    name: "فلفل سیاه",
    price: 80000,
    stars: 4,
    id: 56,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "فلفل سیاه تازه و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/9684/pepper.svg",
  },
  {
    name: "پودر سیر",
    price: 70000,
    stars: 3,
    id: 57,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "پودر سیر خالص و باکیفیت.",
    img: "https://www.svgrepo.com/show/285064/proteins-powder.svg",
  },
  {
    name: "پودر پیاز",
    price: 60000,
    stars: 2,
    id: 58,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "پودر پیاز تازه و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/285064/proteins-powder.svg",
  },
  {
    name: "پودر زنجبیل",
    price: 120000,
    stars: 4,
    id: 59,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "پودر زنجبیل خالص و پرخاصیت.",
    img: "https://www.svgrepo.com/show/285064/proteins-powder.svg",
  },
  {
    name: "پودر فلفل قرمز",
    price: 90000,
    stars: 3,
    id: 60,
    category: "گیاهی",
    discount: 15,
    stock: true,
    description: "پودر فلفل قرمز تند و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/66803/pepper.svg",
  },
  {
    name: "پودر کاری",
    price: 110000,
    stars: 4,
    id: 61,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "پودر کاری خالص و باکیفیت.",
    img: "https://www.svgrepo.com/show/66803/pepper.svg",
  },
  {
    name: "پودر زیره",
    price: 100000,
    stars: 3,
    id: 62,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "پودر زیره خالص و خوش‌عطر.",
    img: "https://www.svgrepo.com/show/66803/pepper.svg",
  },
  {
    name: "گشنیز خشک‌شده",
    price: 80000,
    stars: 2,
    id: 63,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "گشنیز خشک‌شده و خوش‌طعم.",
    img:"https://www.svgrepo.com/show/503730/leaves.svg"
  },
  {
    name: "نعنا خشک‌شده",
    price: 70000,
    stars: 3,
    id: 64,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "نعنا خشک‌شده و خوش‌بو.",
    img:"https://www.svgrepo.com/show/503697/leaves.svg"
  },
  {
    name: "آویشن خشک‌شده",
    price: 90000,
    stars: 4,
    id: 65,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "آویشن خشک‌شده و باکیفیت.",
    img:"https://www.svgrepo.com/show/295449/peas.svg"
  },
  {
    name: "مریم گلی خشک‌شده",
    price: 120000,
    stars: 3,
    id: 66,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "مریم گلی خشک‌شده و خوش‌عطر.",
    img:"https://www.svgrepo.com/show/295424/frittata.svg"
  },
  {
    name: "رزماری خشک‌شده",
    price: 130000,
    stars: 4,
    id: 67,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "رزماری خشک‌شده و باکیفیت.",
    img:"https://www.svgrepo.com/show/295422/smoothie.svg"
  },
  {
    name: "برگ مو خشک‌شده",
    price: 110000,
    stars: 3,
    id: 68,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "برگ مو خشک‌شده و خوش‌عطر.",
    img:"https://www.svgrepo.com/show/503690/leaves.svg"
  },
  {
    name: "جوز هندی خالص",
    price: 150000,
    stars: 4,
    id: 69,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "جوز هندی خالص و باکیفیت.",
    img:"https://www.svgrepo.com/show/503690/leaves.svg"
  },
  {
    name: "میخک خشک‌شده",
    price: 140000,
    stars: 3,
    id: 70,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "میخک خشک‌شده و خوش‌عطر.",
    img:"https://www.svgrepo.com/show/295423/waffle.svg"
  },
  {
    name: "وانیل خالص",
    price: 160000,
    stars: 4,
    id: 71,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "وانیل خالص و خوش‌بو.",
    img:"https://www.creativefabrica.com/wp-content/uploads/2023/05/25/1685017946/Vanilla-580x386.jpg"
  },
  {
    name: "کاکائو خالص",
    price: 180000,
    stars: 5,
    id: 72,
    category: "ارگانیک",
    discount: 20,
    stock: true,
    description: "کاکائو خالص و باکیفیت.",
    img:"https://www.svgrepo.com/show/501912/chocolate.svg"
  },
  
  {
    name: "چای سیاه ارگانیک",
    price: 120000,
    stars: 4,
    id: 75,
    category: "ارگانیک",
    discount: 0,
    stock: false,
    description: "چای سیاه ارگانیک و باکیفیت.",
    img:"https://www.svgrepo.com/show/513350/tea.svg"
  },
  {
    name: "سیر خشک‌شده",
    price: 70000,
    stars: 3,
    id: 81,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "سیر خشک‌شده و باکیفیت.",
    img:"https://www.svgrepo.com/show/503690/leaves.svg"

  },
  {
    name: "پیاز خشک‌شده",
    price: 60000,
    stars: 2,
    id: 82,
    category: "گیاهی",
    discount: 10,
    stock: true,
    description: "پیاز خشک‌شده و خوش‌طعم.",
    img:"https://www.svgrepo.com/show/503690/leaves.svg"

  },
  {
    name: "زنجبیل خشک‌شده",
    price: 120000,
    stars: 4,
    id: 83,
    category: "گیاهی",
    discount: 0,
    stock: false,
    description: "زنجبیل خشک‌شده و پرخاصیت.",
    img:"https://www.svgrepo.com/show/503690/leaves.svg"

  },
  {
    name: "فلفل قرمز خشک‌شده",
    price: 90000,
    stars: 3,
    id: 84,
    category: "گیاهی",
    discount: 15,
    stock: true,
    description: "فلفل قرمز خشک‌شده و تند.",
    img:"https://www.svgrepo.com/show/276578/pepper-spice.svg"
  },
  {
    name: "کاری خالص",
    price: 110000,
    stars: 4,
    id: 85,
    category: "گیاهی",
    discount: 0,
    stock: true,
    description: "کاری خالص و باکیفیت.",
    img:"https://www.svgrepo.com/show/189739/cinnamon-spice.svg"
  },
  {
    name: "زیره خالص",
    price: 100000,
    stars: 3,
    id: 86,
    category: "گیاهی",
    discount: 5,
    stock: true,
    description: "زیره خالص و خوش‌عطر.",
    img:"https://www.svgrepo.com/show/189739/cinnamon-spice.svg"
  },
  {
    name: "آب پرتقال",
    price: 120000,
    stars: 4,
    id: 87,
    category: "آبمیوه",
    discount: 10,
    stock: true,
    description: "آب پرتقال تازه و سرشار از ویتامین C.",
    img: "https://www.svgrepo.com/show/276759/juice.svg"
  },
  {
    name: "آب سیب",
    price: 100000,
    stars: 4,
    id: 88,
    category: "آبمیوه",
    discount: 0,
    stock: true,
    description: "آب سیب طبیعی و شیرین.",
    img: "https://www.svgrepo.com/show/276557/juice.svg"
  },
  {
    name: "آب آناناس",
    price: 150000,
    stars: 5,
    id: 89,
    category: "آبمیوه",
    discount: 15,
    stock: true,
    description: "آب آناناس شیرین و خنک.",
    img: "https://www.svgrepo.com/show/235764/juice.svg"
  },
 
  {
    name: "آب انگور",
    price: 130000,
    stars: 4,
    id: 91,
    category: "آبمیوه",
    discount: 0,
    stock: true,
    description: "آب انگور قرمز و شیرین.",
    img: "https://www.svgrepo.com/show/162164/grape-juice.svg"
  },
  {
    name: "آب گوجه فرنگی",
    price: 80000,
    stars: 3,
    id: 92,
    category: "آبمیوه",
    discount: 10,
    stock: true,
    description: "آب گوجه فرنگی تازه و سرشار از آنتی‌اکسیدان.",
    img: "https://www.svgrepo.com/show/97560/tomato-juice.svg"
  },
  {
    name: "آب انار",
    price: 170000,
    stars: 5,
    id: 93,
    category: "آبمیوه",
    discount: 20,
    stock: true,
    description: "آب انار طبیعی و سرشار از آنتی‌اکسیدان.",
    img: "https://www.svgrepo.com/show/499746/juice.svg"
  },
  {
    name: "آب لیمو شیرین",
    price: 70000,
    stars: 4,
    id: 94,
    category: "آبمیوه",
    discount: 0,
    stock: true,
    description: "آب لیمو تازه و شیرین.",
    img: "https://www.svgrepo.com/show/41420/lemon-juice.svg"
  },
  {
    name: "آب کیوی",
    price: 140000,
    stars: 4,
    id: 95,
    category: "آبمیوه",
    discount: 10,
    stock: true,
    description: "آب کیوی تازه و سرشار از ویتامین C.",
    img: "https://www.svgrepo.com/show/44451/kiwi-juice.svg"
  },
  {
    name: "آب توت فرنگی",
    price: 160000,
    stars: 5,
    id: 96,
    category: "آبمیوه",
    discount: 15,
    stock: true,
    description: "آب توت فرنگی شیرین و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/123342/strawberry-juice.svg"
  },
  {
    name: "آب هندوانه",
    price: 110000,
    stars: 4,
    id: 97,
    category: "آبمیوه",
    discount: 0,
    stock: true,
    description: "آب هندوانه خنک و شیرین.",
    img: "https://www.svgrepo.com/show/152411/watermelon-juice.svg"
  },
  {
    name: "آب خیار",
    price: 75000,
    stars: 3,
    id: 98,
    category: "آبمیوه",
    discount: 5,
    stock: true,
    description: "آب خیار تازه و خنک.",
    img: "https://www.svgrepo.com/show/268926/juice.svg"
  },
  {
    name: "آب آلو",
    price: 95000,
    stars: 4,
    id: 99,
    category: "آبمیوه",
    discount: 0,
    stock: true,
    description: "آب آلو طبیعی و سرشار از فیبر.",
    img: "https://www.svgrepo.com/show/285063/juice.svg"
  },
  {
    name: "آب زردآلو",
    price: 85000,
    stars: 4,
    id: 100,
    category: "آبمیوه",
    discount: 10,
    stock: true,
    description: "آب زردآلو شیرین و خوش‌طعم.",
    img: "https://www.svgrepo.com/show/454327/apricot-food-fruit.svg"
  },
  {
    name: "آب گریپ فروت",
    price: 130000,
    stars: 4,
    id: 101,
    category: "آبمیوه",
    discount: 0,
    stock: true,
    description: "آب گریپ فروت ترش و سرشار از ویتامین C.",
    img: "https://www.svgrepo.com/show/152410/peach-juice.svg"
  }
];

export const navPages = [
  {
    id: 1,
    name: "خانه",
    path: "/home",
    logo: "https://www.svgrepo.com/show/269942/supermarkets-store.svg",
  },
  {
    id: 2,
    name: "محصولات",
    path: "/products",
    logo: "https://www.svgrepo.com/show/269956/healthy-food-apple.svg",
  },
  {
    id: 3,
    name: "درباره ما",
    path: "/about",
    logo: "https://www.svgrepo.com/show/181565/open-book-book.svg",
  },
  {
    id: 4,
    name: "تماس با ما",
    path: "/contact",
    logo: "https://www.svgrepo.com/show/413758/call.svg",
  },
  {
    id: 5,
    name: "سبدخرید",
    path: "",
    logo: "https://www.svgrepo.com/show/269975/upermarket-basket.svg",
  },
];
